### ISSUE TITLE
Queue command pagination

### ISSUE THREAD

**Issue by GodyFromDiscord** [lucidcool/issue-tracker#5]
Issue/Bug: Pagination Issue
Explain what happened: Queue ten songs and then run the queue command, two pages will have md on them with no other songs.

**Comment by GodyFromDiscord** [comment]
Issue is still occurring

**Comment by GodyFromDiscord** [comment]
Issue with `md` has been resolved, but there is still an issue where the same song with recur over two pages, and after a lot of songs are queued the order number for queue will be messed up.

**Comment by Zenternal** [comment]
This issue will be fixed in the rewrite.

**Comment by GodyFromDiscord** [comment]
Closing and adding to known issues
