### ISSUE TITLE
Removing a song from music queue logic error

### ISSUE THREAD

**Issue by KierenPH** [lucidcool/issue-tracker#9]
https://img.kieren.uk/B5lFiPObaa.png

Jamie removed 11 but the bot said 10.

**Comment by GodyFromDiscord** [comment]
Did the bot remove the song from the queue as well or not @KierenPH

**Comment by Zenternal** [comment]
I think I know why this is happening.
Before, the track in position 0 is the current track, but now the current track is stored as a separate object, so we just need to redo some of the logic.

**Comment by GodyFromDiscord** [comment]
As I thought a logic error had occurred

**Comment by VeKett** [comment]
It seems to be working fine for me.
![image](https://user-images.githubusercontent.com/20561327/106368235-12d5f280-6340-11eb-9681-74c87ea2d93c.png)

**Comment by KierenPH** [comment]
I don't know what happened, because it seems to work for you guys, just when we tried. Odd

**Comment by GodyFromDiscord** [comment]
> I don't know what happened, because it seems to work for you guys, just when we tried. Odd

I will run some final checks to see if I can reproduce anything might have just been a one time thing

**Comment by GodyFromDiscord** [comment]
Issue might have been a one time thing, we will keep a look out, thank you
